r"""
Symmetry projection functions.

Functions that implement symmetry projections for states and operators.

Each function takes a (possibly symmetry-broken) variational state and returns
a new state that is invariant under the corresponding symmetry group, with a
variational free energy that is guaranteed to be lower or equal.

Available projections
---------------------
project_parity_like
    :math:`\mathbb{Z}_2` symmetry generated by a product of local unitary
    involutions (e.g. spin-flip parity).

project_conserved_quantity
    Continuous :math:`U(1)` symmetry generated by an additive conserved charge
    (e.g. :math:`S^z_\text{tot}`).  Implemented by zeroing off-diagonal blocks
    in the charge eigenbasis.

project_time_reversal
    :math:`\mathbb{Z}_2` antiunitary symmetry.  For spin-1/2 systems in the
    :math:`S^z` eigenbasis, time reversal acts as complex conjugation
    :math:`\mathcal{K}`.  The projected state is the real part of the density
    matrix, :math:`\tilde{\rho} = (\rho + \rho^*) / 2`.  This removes the
    chiral (imaginary) part that is odd under :math:`\mathcal{K}`, so it is
    the appropriate projection whenever the Hamiltonian has a scalar
    spin-chirality term :math:`\chi_{ijk}` but no external Zeeman field (which
    would itself break time reversal).
"""

from functools import reduce

import numpy as np

from qalma.operators import ScalarOperator
from qalma.operators.states.qutip import QutipDensityOperator
from qalma.qutip_tools.tools import reduce_to_proper_spaces

__all__ = ["project_parity_like", "project_conserved_quantity", "project_time_reversal"]


def project_parity_like(state, op_name: str):
    r"""
    Project on parity-like symmetric states.

    Build a (op_name)-parity symmetry restored state from a broken symmetry
    state.

    op_name must be the name of a local operator, with spectrum $\pm 1$
    """
    if isinstance(state, ScalarOperator):
        return state
    system = state.system
    rho = state.to_qutip_operator()
    site_names = rho.site_names
    block = tuple(sorted(site_names, key=lambda x: site_names[x]))
    rho = rho.to_qutip(block)
    u_gen = reduce(
        lambda x, y: x * y, [system.site_operator(op_name, site) for site in block]
    ).to_qutip(block)
    rho = (u_gen * rho * u_gen.dag() + rho) * 0.5
    return QutipDensityOperator(
        rho,
        system,
        names=site_names,
        normalized=True,
    )


def project_conserved_quantity(state, op_name: str):
    """
    Project on symmetries generated by additive operators.

    Build the average of the gibbs_state invariant under the (diagonal)
    unitaries generated by the local operator `op_name`.
    """
    if isinstance(state, ScalarOperator):
        return state
    rho_qutip = state.to_qutip_operator()
    system = rho_qutip.system
    site_names = rho_qutip.site_names
    block = tuple(sorted(site_names, key=lambda name: site_names[name]))
    if not block:
        return state

    try:
        conserved = reduce(
            lambda x, y: x + y, (system.site_operator(op_name, site) for site in block)
        )
    except TypeError as exc:
        raise ValueError(
            f"{op_name} is not a valid local operator name for some sites."
        ) from exc

    return QutipDensityOperator(
        reduce_to_proper_spaces(rho_qutip.operator, conserved.to_qutip(block)),
        rho_qutip.system,
        names=site_names,
        normalized=True,
    )


def project_time_reversal(state):
    r"""Project onto the time-reversal-symmetric subspace.

    Time reversal :math:`\mathcal{T}` is an antiunitary involution.  For
    spin-:math:`\tfrac{1}{2}` systems in the :math:`S^z` eigenbasis it acts as
    complex conjugation :math:`\mathcal{K}` (up to a global phase), so a state
    :math:`\rho` transforms as

    .. math::

        \mathcal{T}[\rho] = \rho^*

    where the star denotes element-wise complex conjugation in the
    :math:`S^z` eigenbasis.  The :math:`\mathcal{T}`-projected state is then

    .. math::

        \tilde{\rho}
            = \tfrac{1}{2}\bigl(\rho + \rho^*\bigr)
            = \operatorname{Re}(\rho)

    which is manifestly Hermitian, positive semi-definite, and
    :math:`\mathcal{T}`-invariant.

    **When to use this projection**

    The scalar spin-chirality operator
    :math:`\chi_{ijk} = \vec{S}_i \cdot (\vec{S}_j \times \vec{S}_k)` is *odd*
    under :math:`\mathcal{T}` (it is purely imaginary in the :math:`S^z`
    basis).  If the Hamiltonian contains only :math:`\mathcal{T}`-even terms
    (Heisenberg exchange, transverse fields, …) plus a chiral term with a
    *real* coupling :math:`\chi`, then the exact Gibbs state is
    :math:`\mathcal{T}`-invariant and the projection is exact.

    When a Zeeman field :math:`B\sum_i S^z_i` is also present, time-reversal
    is explicitly broken; this projection should **not** be applied in that
    case.

    **Variational free-energy bound**

    Because :math:`\tilde{\rho}` is a convex combination of :math:`\rho` and
    :math:`\mathcal{T}[\rho]`, and :math:`F` is convex in :math:`\rho`, we
    have

    .. math::

        F[\tilde{\rho}]
            \leq \tfrac{1}{2}\bigl(F[\rho] + F[\mathcal{T}[\rho]]\bigr)
            = F[\rho]

    where the last equality holds when :math:`[H, \mathcal{T}] = 0`, i.e.
    when the Hamiltonian is :math:`\mathcal{T}`-invariant.

    Parameters
    ----------
    state : ProductDensityOperator or QutipDensityOperator
        The (possibly :math:`\mathcal{T}`-broken) variational state.

    Returns
    -------
    QutipDensityOperator
        The :math:`\mathcal{T}`-projected state :math:`\operatorname{Re}(\rho)`,
        normalised to unit trace.

    See Also
    --------
    project_parity_like : :math:`\mathbb{Z}_2` unitary symmetry projection.
    project_conserved_quantity : :math:`U(1)` symmetry projection.

    Examples
    --------
    >>> from qalma.projections.symmetries import project_time_reversal
    >>> sigma_T = project_time_reversal(sigma)
    >>> print(f"F before: {compute_free_energy(sigma,   beta * ham):.6f}")
    >>> print(f"F after:  {compute_free_energy(sigma_T, beta * ham):.6f}")
    """
    if isinstance(state, ScalarOperator):
        return state

    rho_qutip = state.to_qutip_operator()
    site_names = rho_qutip.site_names
    block = tuple(sorted(site_names, key=lambda name: site_names[name]))

    rho = rho_qutip.to_qutip(block)

    # Complex conjugation in the current (S^z eigenbasis) representation.
    # Re(rho) = (rho + rho*) / 2.  Since rho is already Hermitian,
    # rho* = rho.T, so Re(rho) = (rho + rho.T) / 2, but it is cheaper and
    # numerically cleaner to just take the real part of the dense matrix.
    import qutip

    rho_real = qutip.Qobj(
        np.real(rho.full()),
        dims=rho.dims,
        isherm=True,
    )

    # Normalise: Re(rho) has the same trace as rho (since rho is Hermitian
    # and its diagonal is real), but we call normalized=True to be safe.
    return QutipDensityOperator(
        rho_real,
        rho_qutip.system,
        names=site_names,
        normalized=True,
    )
